"""Shared loader for `.codeyam/cache/step-metadata.json`.

Both `editor-step-hook.py` (PostToolUse / Stop / UserPromptSubmit) and
`editor-pretool-hook.py` (PreToolUse) read this cache. Keeping a single
implementation here means a schema change is a one-file edit.

The cache is regenerated by `codeyam-editor-dev editor verify-build`,
which is wired into the audit gate, the advance gate, and the
embedded pre-commit hook. Schema versions 1 (label/description/
restriction only) and 2 (adds slug + capability tag projections)
both load successfully; v1 callers see empty capability arrays so the
hook degrades to "allow everything" rather than blocking on a stale
cache after a binary downgrade.
"""

import json
import os
import shutil


CACHE_REL_PATH = os.path.join(".codeyam", "cache", "step-metadata.json")

SUPPORTED_SCHEMA_VERSIONS = (1, 2)


def cli_command():
    """Return the codeyam-editor CLI name to surface to the user.

    Prefers `codeyam-editor-dev` (local-dev rebuild wrapper) when on
    PATH; otherwise falls back to the canonical `codeyam-editor` binary.
    Cloud VM images only install `codeyam-editor`, so probing PATH at
    emit time eliminates `command not found` noise that would otherwise
    flood every session there.
    """
    if shutil.which("codeyam-editor-dev"):
        return "codeyam-editor-dev"
    return "codeyam-editor"


def _empty_mode_table():
    return {
        "total": 0,
        "labels": {},
        "descriptions": {},
        "restrictions": {},
        "slugsByStep": {},
        "codeChangeSlugs": [],
        "commitSlugs": [],
        "pushSlugs": [],
        "previewRequiredSlugs": [],
    }


def _kv_pairs_to_int_dict(pairs):
    """Cache mode-table fields are JSON arrays of [step, value] pairs.
    Convert to {int(step): value} for O(1) lookup."""
    out = {}
    for entry in pairs or []:
        try:
            step_num, value = entry
            out[int(step_num)] = value
        except (TypeError, ValueError):
            continue
    return out


def _string_list(raw):
    """Normalize a JSON value to a list[str]. Non-list inputs and
    non-string members are dropped — the hook treats malformed entries
    as if they were absent rather than blocking on parse error."""
    if not isinstance(raw, list):
        return []
    return [s for s in raw if isinstance(s, str)]


def load_step_metadata(project_dir):
    """Load the per-mode step metadata cache. Returns
    {"ui": <mode_table>, "backend": <mode_table>} where each
    mode_table carries label/description/restriction dicts plus
    slug-keyed capability arrays.

    Falls back to empty tables on any read/parse error so the hook
    keeps firing (just without labels and with no slug allowlists)
    when the cache is missing or a different binary version wrote a
    shape we don't understand. Empty capability arrays mean the
    pretool hook treats every slug as ungated — degrade to "allow"
    rather than brick the session on cache skew."""
    cache_path = os.path.join(project_dir, CACHE_REL_PATH)
    fallback = {"ui": _empty_mode_table(), "backend": _empty_mode_table()}
    try:
        with open(cache_path, "r") as f:
            raw = json.load(f)
    except (IOError, json.JSONDecodeError):
        return fallback
    if not isinstance(raw, dict) or raw.get("schemaVersion") not in SUPPORTED_SCHEMA_VERSIONS:
        return fallback
    out = {}
    for mode_key in ("ui", "backend"):
        mode_raw = raw.get(mode_key) or {}
        out[mode_key] = {
            "total": int(mode_raw.get("total", 0) or 0),
            "labels": _kv_pairs_to_int_dict(mode_raw.get("labels", [])),
            "descriptions": _kv_pairs_to_int_dict(mode_raw.get("descriptions", [])),
            "restrictions": _kv_pairs_to_int_dict(mode_raw.get("restrictions", [])),
            "slugsByStep": _kv_pairs_to_int_dict(mode_raw.get("slugsByStep", [])),
            "codeChangeSlugs": _string_list(mode_raw.get("codeChangeSlugs")),
            "commitSlugs": _string_list(mode_raw.get("commitSlugs")),
            "pushSlugs": _string_list(mode_raw.get("pushSlugs")),
            "previewRequiredSlugs": _string_list(mode_raw.get("previewRequiredSlugs")),
        }
    return out


def resolve_mode_table(state, metadata):
    """Pick the mode table (ui or backend) matching the active state.
    Defaults to UI when `mode` is missing — matches the legacy
    behavior where state files predating multi-mode support are
    treated as UI sessions."""
    mode = (state.get("mode") or "ui") if isinstance(state, dict) else "ui"
    if mode == "backend":
        return mode, metadata.get("backend", _empty_mode_table())
    return mode, metadata.get("ui", _empty_mode_table())
