import SwiftUI

// GENERATED by `codeyam-editor editor isolate` — do not edit by hand.
//
// Renders a single component in isolation on the booted simulator, selected by
// the CODEYAM_ISOLATE_COMPONENT / CODEYAM_ISOLATE_SCENARIO env vars (set via a component scenario's
// deviceState.launchEnv, delivered to the app as SIMCTL_CHILD_* on launch).
// Returns nil when no component is selected so the app renders its normal root.
//
// Wire this into your @main App once:
//   WindowGroup { CodeyamIsolationHost.root() ?? AnyView(ContentView()) }
public enum CodeyamIsolationHost {
    public static func root() -> AnyView? {
        let env = ProcessInfo.processInfo.environment
        guard let component = env["CODEYAM_ISOLATE_COMPONENT"] else { return nil }
        let scenario = env["CODEYAM_ISOLATE_SCENARIO"] ?? "Default"
        switch component {
        case "AskCoachHeader":
            return AnyView(AskCoachHeaderIsolated(scenario: scenario))
        default:
            return AnyView(Text("Unknown isolated component: \(component)"))
        }
    }
}
